/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'david' at '8/6/18 2:44 PM' with Gradle 2.10
 *
 * @author david, @date 8/6/18 2:44 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
